### ISSUE TITLE
Notation clash between Sniper and Mathcomp's ssrnotations module

### ISSUE THREAD

**Issue by anton-trunov** [smtcoq/sniper#5]
```coq
From mathcomp Require Import ssrfun.
From Sniper Require Import Sniper.
```

produces the following error:
```
Error: Notation "_ .[ _ ]" is already defined at level 2 with arguments constr
at level 2, constr while it is now required to be at level 50 with arguments constr
at next level, constr.
```

This is because Mathcomp's `ssrfun` exports the [`ssrnotations`](https://github.com/math-comp/math-comp/blob/727c50fea5f224776f5069eb79250ef2e32ff558/mathcomp/ssreflect/ssrnotations.v#L34) module. Note that Coq's own `ssrfun` module does not have this notation clash.

Perhaps, Sniper's notations could be hidden behind a module, like `ListNotations` in Coq's stdlib? Or is it exported from somewhere else?

**Comment by vblot** [comment]
Thanks for this bug report. The bug was actually part of SMTCoq, and has been fixed in https://github.com/smtcoq/smtcoq/commit/01431eb67ed566baa2268f1382d687bc7b020d1c

**Comment by anton-trunov** [comment]
Thank you for taking care of this!
